development:
  adapter: postgresql
  database: crambear_development
  host: localhost

test:
  adapter: postgresql
  database: crambear_test
  host: localhost


#development:
#  adapter: postgresql
#  database: crambear_dev
#  host: localhost
#test:
#  adapter: postgresql
#  database: crambear_test
#  host: localhost


#dummy to get assets:precompile to work
#see http://devcenter.heroku.com/articles/rails31_heroku_cedar
production:
  adapter: postgresql
  database: crambear_production
  username: postgres
  password: pwwwwww12

